import { CssBaseline, ThemeProvider } from '@material-ui/core';
import { theme } from '../themes/theme';
import Head from 'next/head';
import { Header } from '../components/Header';
import { AppProps } from 'next/app';
import { wrapper } from '../store/store';

import 'macro-css';
import '../styles/globals.scss';
import { parseCookies } from 'nookies';
import { setUserData } from '../store/slices/user/user';
import { Api } from '../api';

function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Tjurnal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={'true'} />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;0,900;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header />
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <Component {...pageProps} />
      </ThemeProvider>
    </>
  );
}

export default wrapper.withRedux(App);

const getInitialProps = wrapper.getInitialAppProps((store) => async ({ ctx, Component }) => {
  try {
    const { authToken } = parseCookies(ctx);

    const userData = await Api(ctx).user.getMe();

    store.dispatch(setUserData(userData));
  } catch (error) {
    if (ctx.asPath === '/write') {
      ctx.res.writeHead(302, {
        Location: '/403',
      });
      ctx.res.end();
    }
  }
  return {
    pageProps: {
      ...(Component.getInitialProps ? await Component.getInitialProps({ ...ctx, store }) : {}),
    },
  };
});
