import Head from 'next/head';
import { Header } from '../components/Header';
import { Paper, Typography } from '@material-ui/core';
import Image from 'next/image';
import { Post } from '../components/Post';
import { LeftMenu } from '../components/LeftMenu';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tjurnal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={'true'} />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;0,900;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header />
      <div className="wrapper">
        <div className="leftSide">
          <LeftMenu />
        </div>
        <div className="content">
          <Post />
          <Post />
          <Post />
          <Post />
        </div>
        <div className="rightSide"></div>
      </div>
    </div>
  );
}
